---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-k8s

---
apiVersion: v1
kind: Service
metadata:
  name: hello-k8-service
  namespace: hello-k8s
spec:
  selector:
    app: python
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8-app
  namespace: hello-k8s
  labels:
    app: pythonk8
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: hello-python
          image: 191295/test:tagname
          imagePullPolicy: always
          ports:
            - containerPort: 5000
